server:
  port: 8888
  servlet:
    context-path: /cloudconfigservice

eureka:
  client:
    serviceUrl:
      defaultZone: http://${discovery-service:localhost}:8761/eureka

spring:
  application:
    name: cloud-config-service
  profiles:
    active: local
  cloud:
    config:
      server:
        git:
          uri: https://github.com/raghupulishetti/config-service
          skipSslValidation: true
