server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_URL:localhost}:8761/eureka

spring:
  application:
    name: GATEWAY-SERVICE

  profiles:
    active: local

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY