server:
  port: 9100
  servlet:
    context-path: /userservice

eureka:
  client:
    serviceUrl:
      defaultZone: http://${discovery-service:localhost}:8761/eureka

spring:
  application:
    name: USER-SERVICE
  profiles:
    active: local

jwt:
  secret: SecretKey1234

