server:
  port: 9002
  servlet:
    context-path: /userservice

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: USER-SERVICE
  profiles:
    active: local

