server:
  port: 9001
  servlet:
    context-path: /productservice

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka

spring:
  application:
    name: PRODUCT-SERVICE
  profiles:
    active: local

