server:
  port: 9001
  servlet:
    context-path: /productservice

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_URL:localhost}:8761/eureka

spring:
  application:
    name: PRODUCT-SERVICE
  profiles:
    active: local

  config:
    import: optional:configserver:http://${cloud-config-service:localhost}:8888

management:
  endpoint:
    web:
      exposure:
        include: "*"

